[package]
name = "minigrep_plus"
version = "0.2.1"
edition = "2021"
description = "A minigrep/grep inspired crate that adds error handling and a help function to the book minigrep."
license = "MIT"

[dependencies]
